- hosts: nodes
  become: yes
  tasks:

  - name: Set Broker ID
    set_fact:
      broker_id: "{{ groups['nodes'].index(inventory_hostname) + 1 }}"

  - name: Set zookeeper connection
    set_fact:
      zookeeper_connection: "{{ groups['nodes'] | map ('extract', hostvars, ['ansible_default_ipv4', 'address']) | product([':2181']) | map('join') | join(',') }}"

  - name: install openjdk
    apt:
      pkg:
      - libxt-dev
      - openjdk-11-jdk-headless
      - openjdk-11-jdk
      update_cache: yes

  - name: install wget
    apt:
      name: wget
      state: present

  - name: install gnupg2
    apt:
      name: gnupg2
      state: present


  - name: install software-properties-common
    apt:
      name: software-properties-common
      state: present


  - name: install net-tools
    apt:
      name: net-tools
      state: present


  - name: install iputils-ping
    apt:
      name: iputils-ping
      state: present

  - name: add confluent apt-key
    apt_key:
      url: https://packages.confluent.io/deb/6.1/archive.key
      state: present

  - name: add confluent's APT repository
    apt_repository:
      repo: deb https://packages.confluent.io/deb/6.1 stable main
      state: present
      filename: 'confluent'

  - name: install confluent community
    apt:
      name: confluent-community-2.13
      state: present
      update_cache: yes

#-------------------------------------------------------------------------------
# Install Kafka Connect for MongoDB
#-------------------------------------------------------------------------------

  - name: Download confluent-hub
    get_url:
      url: http://client.hub.confluent.io/confluent-hub-client-latest.tar.gz
      dest: /opt
        # mode: '0440'

  - name: Create a confluent hub directory
    ansible.builtin.file:
      path: /opt/confluent-hub
      state: directory
      mode: '0755'

  - name: extract confuent-hub
    ansible.builtin.unarchive:
      src: /opt/confluent-hub-client-latest.tar.gz
      dest: /opt/confluent-hub
      remote_src: yes

  - name: Run command to install kafka connect for mongodb
    ansible.builtin.command:
      argv:
        - /opt/confluent-hub/bin/confluent-hub
        - install
        - --no-prompt
        - mongodb/kafka-connect-mongodb:1.5.1

#-------------------------------------------------------------------------------
# Disable swap for Kafka
# - Check whether swap is on: swapon -s
# - Get the swap UUID using blkid
# - Update fstab to disable swap
#-------------------------------------------------------------------------------

#   - name: install libblkid-dev
#     apt:
#       name: libblkid-dev
#       state: present
# 
#   - name: x
#     shell: blkid -s UUID -o value {{ ebs_swap }}
#     register: blkid_out
# 
#   - name: y
#     lineinfile:
#       path: /etc/fstab
#       regexp: "^UUID={{ blkid_out.stdout }}"
#       line: "UUID={{ blkid_ut.stdout }} swap  swap  defaults 0 0"
